version: '3.7'
services:
  web:
    image: strund3r/arscrift-web
    ports:
      - "80:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        monitor: 2m
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 10s
        monitor: 2m
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  dashboard:
    image: strund3r/arscrift-dashboard
    ports:
      - "81:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        monitor: 2m
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 10s
        monitor: 2m
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  prometheus:
    image: strund3r/prometheus
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    networks:
      - backend
    ports:
      - 9090:9090

  node-exporter:
    image: strund3r/node-exporter
    hostname: '{{.Node.ID}}'
    volumes:
      - /proc:/usr/proc
      - /sys:/usr/sys
      - /:/rootfs
    deploy:
      mode: global
    networks:
      - backend
    ports:
      - 9100:9100

  alertmanager:
    image: strund3r/alertmanager
    volumes:
      - ./conf/alertmanager/:/etc/alertmanager/
    networks:
      - backend
    ports:
      - 9093:9093

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    deploy:
      mode: global
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - grafana.config
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000

networks:
  frontend:
  backend:

volumes:
    prometheus_data:
    grafana_data: