version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    docker: # run the steps with Docker
      - image: circleci/node:8-browsers # ...with this image as the primary container; this is where all `steps` will run

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    working_directory: ~/arscrift # directory where steps will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build and push docker image to docker hub
      - run:
          name: Build image
          command: docker build -t strund3r/arscrift-web:$CIRCLE_BUILD_NUM . && docker build -t strund3r/arscrift-web:latest .
      - run:
          name: Push image to Docker Hub
          command: docker push strund3r/arscrift-web

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/arscrift
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Decrpyt Secrets
          command: openssl enc -d -aes-256-ecb -md md5 -in arscrift.pem.enc -out arscrift.pem -k $PEM_SECRET_KEY
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy Over SSH
          command: chmod +x deploy.sh && ./deploy.sh

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build: # build application
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - master
      - deploy: # deploy master branch to the server
          requires:
            - build
          filters:
            branches:
              only:
                - master
